name: ThunderFly TF-GCS buildroot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1,2,3,4,5


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install sed make binutils build-essential gcc g++ bash patch \
          gzip bzip2 perl tar cpio unzip rsync file bc wget python3 cvs git \
          mercurial subversion

      - name: Checkout Buildroot sources
        run: git clone --depth=1 -b tfgcs git@github.com:ThunderFly-aerospace/TF-buildroot.git

      - name: Seeed buildroot cache
        uses: actions/cache@v2
        env:
          cache-name: cache-download-files
        with:
          path: ${{ github.workspace }}/TF-buildroot/dl/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/TF-buildroot/configs/ThunderFly_64_defconfig') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Configure Buildroot
        run: |
          cd ${{ github.workspace }}/TF-buildroot/
          make ThunderFly_64_defconfig

      - name: Build
        run: |
          cd ${{ github.workspace }}/TF-buildroot/
          make

      - name: Pack
        run: |
          cd ${{ github.workspace }}/TF-buildroot/output/images/
          tar -zcvf buildroot-image.tar.gz sdcard.img
          echo "PACKAGE=${{ github.workspace }}/TF-buildroot/output/images/buildroot-image.tar.gz" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: buildroot deploy
          path: ${{env.PACKAGE}}
